### ISSUE TITLE
train 시 사용하신 csv 형식을 알 수 있을까요?

### ISSUE THREAD

**Issue by sjhyeon2** [Beomi/easy-lm-trainer#2]
@Beomi 님 안녕하세요. 

python main.py \
    --model_name='EleutherAI/polyglot-ko-5.8b' \
    --train_file_path='./data/ko_alpaca_data_sep.csv' \
    --num_train_epochs=3 \
    --data_text_column='text' \
    --block_size=1024 \
    --batch_size=2 \
    --gradient_accumulation_steps=64 \
    --learning_rate=0.00002 \
    --fp16=True \

위의 예제로 올려주셨는데,
ko_alpaca_data_sep.csv 형식 샘플을 알고 싶습니다.

**Comment by Beomi** [comment]
안녕하세요,
해당 부분은 단순히 아래와 같이 `text` (이것도 설정에서 바꾸실수 있습니다.) 컬럼만 있는 csv이면 됩니다.

```csv
text,
### 명령문: 파이썬으로 피보나치 수열을 짜 보세요.\n\n## 답변: def fibonacii(n): ....[생략]
```

jsonl이라면 아래와 같이 마련하시면 됩니다.

```json
{"text": "### 명령문: 파이썬으로 피보나치 수열을 짜 보세요.\n\n## 답변: def fibonacii(n): ....[생략]"}
{"text": "### 명령문: 다음 셋 중 홀수번째인 것은?\n\n### 입력: 인스타그램, 트위터, 텔레그램\n\n## 답변: 텔레그램"}
```
